/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as StudentsIndexRouteImport } from './routes/students/index'
import { Route as QuestionsIndexRouteImport } from './routes/questions/index'
import { Route as MentorsIndexRouteImport } from './routes/mentors/index'
import { Route as GradesIndexRouteImport } from './routes/grades/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as TasksIdRouteImport } from './routes/tasks/$id'
import { Route as StudentsIdRouteImport } from './routes/students/$id'
import { Route as MentorsIdRouteImport } from './routes/mentors/$id'
import { Route as GradesIdRouteImport } from './routes/grades/$id'
import { Route as CoursesIdIndexRouteImport } from './routes/courses/$id/index'
import { Route as CoursesIdChaptersRouteRouteImport } from './routes/courses/$id/chapters/route'
import { Route as TasksSubmissionsIdSubmissionIdRouteImport } from './routes/tasks/submissions/$id/$submissionId'
import { Route as CoursesIdChaptersChapterIdIndexRouteImport } from './routes/courses/$id/chapters/$chapterId/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIndexRoute = QuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsIndexRoute = MentorsIndexRouteImport.update({
  id: '/mentors/',
  path: '/mentors/',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesIndexRoute = GradesIndexRouteImport.update({
  id: '/grades/',
  path: '/grades/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdRoute = StudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsIdRoute = MentorsIdRouteImport.update({
  id: '/mentors/$id',
  path: '/mentors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesIdRoute = GradesIdRouteImport.update({
  id: '/grades/$id',
  path: '/grades/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIdIndexRoute = CoursesIdIndexRouteImport.update({
  id: '/courses/$id/',
  path: '/courses/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIdChaptersRouteRoute = CoursesIdChaptersRouteRouteImport.update({
  id: '/courses/$id/chapters',
  path: '/courses/$id/chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksSubmissionsIdSubmissionIdRoute =
  TasksSubmissionsIdSubmissionIdRouteImport.update({
    id: '/tasks/submissions/$id/$submissionId',
    path: '/tasks/submissions/$id/$submissionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesIdChaptersChapterIdIndexRoute =
  CoursesIdChaptersChapterIdIndexRouteImport.update({
    id: '/$chapterId/',
    path: '/$chapterId/',
    getParentRoute: () => CoursesIdChaptersRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/grades/$id': typeof GradesIdRoute
  '/mentors/$id': typeof MentorsIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/courses': typeof CoursesIndexRoute
  '/grades': typeof GradesIndexRoute
  '/mentors': typeof MentorsIndexRoute
  '/questions': typeof QuestionsIndexRoute
  '/students': typeof StudentsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/courses/$id/chapters': typeof CoursesIdChaptersRouteRouteWithChildren
  '/courses/$id': typeof CoursesIdIndexRoute
  '/tasks/submissions/$id/$submissionId': typeof TasksSubmissionsIdSubmissionIdRoute
  '/courses/$id/chapters/$chapterId': typeof CoursesIdChaptersChapterIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/grades/$id': typeof GradesIdRoute
  '/mentors/$id': typeof MentorsIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/courses': typeof CoursesIndexRoute
  '/grades': typeof GradesIndexRoute
  '/mentors': typeof MentorsIndexRoute
  '/questions': typeof QuestionsIndexRoute
  '/students': typeof StudentsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/courses/$id/chapters': typeof CoursesIdChaptersRouteRouteWithChildren
  '/courses/$id': typeof CoursesIdIndexRoute
  '/tasks/submissions/$id/$submissionId': typeof TasksSubmissionsIdSubmissionIdRoute
  '/courses/$id/chapters/$chapterId': typeof CoursesIdChaptersChapterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/grades/$id': typeof GradesIdRoute
  '/mentors/$id': typeof MentorsIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/grades/': typeof GradesIndexRoute
  '/mentors/': typeof MentorsIndexRoute
  '/questions/': typeof QuestionsIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/courses/$id/chapters': typeof CoursesIdChaptersRouteRouteWithChildren
  '/courses/$id/': typeof CoursesIdIndexRoute
  '/tasks/submissions/$id/$submissionId': typeof TasksSubmissionsIdSubmissionIdRoute
  '/courses/$id/chapters/$chapterId/': typeof CoursesIdChaptersChapterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/grades/$id'
    | '/mentors/$id'
    | '/students/$id'
    | '/tasks/$id'
    | '/courses'
    | '/grades'
    | '/mentors'
    | '/questions'
    | '/students'
    | '/tasks'
    | '/courses/$id/chapters'
    | '/courses/$id'
    | '/tasks/submissions/$id/$submissionId'
    | '/courses/$id/chapters/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/grades/$id'
    | '/mentors/$id'
    | '/students/$id'
    | '/tasks/$id'
    | '/courses'
    | '/grades'
    | '/mentors'
    | '/questions'
    | '/students'
    | '/tasks'
    | '/courses/$id/chapters'
    | '/courses/$id'
    | '/tasks/submissions/$id/$submissionId'
    | '/courses/$id/chapters/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/grades/$id'
    | '/mentors/$id'
    | '/students/$id'
    | '/tasks/$id'
    | '/courses/'
    | '/grades/'
    | '/mentors/'
    | '/questions/'
    | '/students/'
    | '/tasks/'
    | '/courses/$id/chapters'
    | '/courses/$id/'
    | '/tasks/submissions/$id/$submissionId'
    | '/courses/$id/chapters/$chapterId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  GradesIdRoute: typeof GradesIdRoute
  MentorsIdRoute: typeof MentorsIdRoute
  StudentsIdRoute: typeof StudentsIdRoute
  TasksIdRoute: typeof TasksIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  GradesIndexRoute: typeof GradesIndexRoute
  MentorsIndexRoute: typeof MentorsIndexRoute
  QuestionsIndexRoute: typeof QuestionsIndexRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  CoursesIdChaptersRouteRoute: typeof CoursesIdChaptersRouteRouteWithChildren
  CoursesIdIndexRoute: typeof CoursesIdIndexRoute
  TasksSubmissionsIdSubmissionIdRoute: typeof TasksSubmissionsIdSubmissionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/': {
      id: '/questions/'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors/': {
      id: '/mentors/'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades/': {
      id: '/grades/'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof GradesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id': {
      id: '/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof StudentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors/$id': {
      id: '/mentors/$id'
      path: '/mentors/$id'
      fullPath: '/mentors/$id'
      preLoaderRoute: typeof MentorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades/$id': {
      id: '/grades/$id'
      path: '/grades/$id'
      fullPath: '/grades/$id'
      preLoaderRoute: typeof GradesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$id/': {
      id: '/courses/$id/'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$id/chapters': {
      id: '/courses/$id/chapters'
      path: '/courses/$id/chapters'
      fullPath: '/courses/$id/chapters'
      preLoaderRoute: typeof CoursesIdChaptersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/submissions/$id/$submissionId': {
      id: '/tasks/submissions/$id/$submissionId'
      path: '/tasks/submissions/$id/$submissionId'
      fullPath: '/tasks/submissions/$id/$submissionId'
      preLoaderRoute: typeof TasksSubmissionsIdSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$id/chapters/$chapterId/': {
      id: '/courses/$id/chapters/$chapterId/'
      path: '/$chapterId'
      fullPath: '/courses/$id/chapters/$chapterId'
      preLoaderRoute: typeof CoursesIdChaptersChapterIdIndexRouteImport
      parentRoute: typeof CoursesIdChaptersRouteRoute
    }
  }
}

interface CoursesIdChaptersRouteRouteChildren {
  CoursesIdChaptersChapterIdIndexRoute: typeof CoursesIdChaptersChapterIdIndexRoute
}

const CoursesIdChaptersRouteRouteChildren: CoursesIdChaptersRouteRouteChildren =
  {
    CoursesIdChaptersChapterIdIndexRoute: CoursesIdChaptersChapterIdIndexRoute,
  }

const CoursesIdChaptersRouteRouteWithChildren =
  CoursesIdChaptersRouteRoute._addFileChildren(
    CoursesIdChaptersRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  GradesIdRoute: GradesIdRoute,
  MentorsIdRoute: MentorsIdRoute,
  StudentsIdRoute: StudentsIdRoute,
  TasksIdRoute: TasksIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  GradesIndexRoute: GradesIndexRoute,
  MentorsIndexRoute: MentorsIndexRoute,
  QuestionsIndexRoute: QuestionsIndexRoute,
  StudentsIndexRoute: StudentsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  CoursesIdChaptersRouteRoute: CoursesIdChaptersRouteRouteWithChildren,
  CoursesIdIndexRoute: CoursesIdIndexRoute,
  TasksSubmissionsIdSubmissionIdRoute: TasksSubmissionsIdSubmissionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
