/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuestionsIndexRouteImport } from './routes/questions/index'
import { Route as MentorsIndexRouteImport } from './routes/mentors/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as MentorsIdRouteImport } from './routes/mentors/$id'
import { Route as CoursesIdIndexRouteImport } from './routes/courses/$id/index'
import { Route as CoursesIdChaptersRouteRouteImport } from './routes/courses/$id/chapters/route'
import { Route as CoursesIdChaptersChapterIdIndexRouteImport } from './routes/courses/$id/chapters/$chapterId/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIndexRoute = QuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsIndexRoute = MentorsIndexRouteImport.update({
  id: '/mentors/',
  path: '/mentors/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsIdRoute = MentorsIdRouteImport.update({
  id: '/mentors/$id',
  path: '/mentors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIdIndexRoute = CoursesIdIndexRouteImport.update({
  id: '/courses/$id/',
  path: '/courses/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIdChaptersRouteRoute = CoursesIdChaptersRouteRouteImport.update({
  id: '/courses/$id/chapters',
  path: '/courses/$id/chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIdChaptersChapterIdIndexRoute =
  CoursesIdChaptersChapterIdIndexRouteImport.update({
    id: '/$chapterId/',
    path: '/$chapterId/',
    getParentRoute: () => CoursesIdChaptersRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mentors/$id': typeof MentorsIdRoute
  '/courses': typeof CoursesIndexRoute
  '/mentors': typeof MentorsIndexRoute
  '/questions': typeof QuestionsIndexRoute
  '/courses/$id/chapters': typeof CoursesIdChaptersRouteRouteWithChildren
  '/courses/$id': typeof CoursesIdIndexRoute
  '/courses/$id/chapters/$chapterId': typeof CoursesIdChaptersChapterIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mentors/$id': typeof MentorsIdRoute
  '/courses': typeof CoursesIndexRoute
  '/mentors': typeof MentorsIndexRoute
  '/questions': typeof QuestionsIndexRoute
  '/courses/$id/chapters': typeof CoursesIdChaptersRouteRouteWithChildren
  '/courses/$id': typeof CoursesIdIndexRoute
  '/courses/$id/chapters/$chapterId': typeof CoursesIdChaptersChapterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mentors/$id': typeof MentorsIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/mentors/': typeof MentorsIndexRoute
  '/questions/': typeof QuestionsIndexRoute
  '/courses/$id/chapters': typeof CoursesIdChaptersRouteRouteWithChildren
  '/courses/$id/': typeof CoursesIdIndexRoute
  '/courses/$id/chapters/$chapterId/': typeof CoursesIdChaptersChapterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mentors/$id'
    | '/courses'
    | '/mentors'
    | '/questions'
    | '/courses/$id/chapters'
    | '/courses/$id'
    | '/courses/$id/chapters/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mentors/$id'
    | '/courses'
    | '/mentors'
    | '/questions'
    | '/courses/$id/chapters'
    | '/courses/$id'
    | '/courses/$id/chapters/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/mentors/$id'
    | '/courses/'
    | '/mentors/'
    | '/questions/'
    | '/courses/$id/chapters'
    | '/courses/$id/'
    | '/courses/$id/chapters/$chapterId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MentorsIdRoute: typeof MentorsIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  MentorsIndexRoute: typeof MentorsIndexRoute
  QuestionsIndexRoute: typeof QuestionsIndexRoute
  CoursesIdChaptersRouteRoute: typeof CoursesIdChaptersRouteRouteWithChildren
  CoursesIdIndexRoute: typeof CoursesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/': {
      id: '/questions/'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors/': {
      id: '/mentors/'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors/$id': {
      id: '/mentors/$id'
      path: '/mentors/$id'
      fullPath: '/mentors/$id'
      preLoaderRoute: typeof MentorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$id/': {
      id: '/courses/$id/'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$id/chapters': {
      id: '/courses/$id/chapters'
      path: '/courses/$id/chapters'
      fullPath: '/courses/$id/chapters'
      preLoaderRoute: typeof CoursesIdChaptersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$id/chapters/$chapterId/': {
      id: '/courses/$id/chapters/$chapterId/'
      path: '/$chapterId'
      fullPath: '/courses/$id/chapters/$chapterId'
      preLoaderRoute: typeof CoursesIdChaptersChapterIdIndexRouteImport
      parentRoute: typeof CoursesIdChaptersRouteRoute
    }
  }
}

interface CoursesIdChaptersRouteRouteChildren {
  CoursesIdChaptersChapterIdIndexRoute: typeof CoursesIdChaptersChapterIdIndexRoute
}

const CoursesIdChaptersRouteRouteChildren: CoursesIdChaptersRouteRouteChildren =
  {
    CoursesIdChaptersChapterIdIndexRoute: CoursesIdChaptersChapterIdIndexRoute,
  }

const CoursesIdChaptersRouteRouteWithChildren =
  CoursesIdChaptersRouteRoute._addFileChildren(
    CoursesIdChaptersRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MentorsIdRoute: MentorsIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  MentorsIndexRoute: MentorsIndexRoute,
  QuestionsIndexRoute: QuestionsIndexRoute,
  CoursesIdChaptersRouteRoute: CoursesIdChaptersRouteRouteWithChildren,
  CoursesIdIndexRoute: CoursesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
