/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as StudentsIndexRouteImport } from './routes/students/index'
import { Route as QuestionsIndexRouteImport } from './routes/questions/index'
import { Route as QuestionbankIndexRouteImport } from './routes/questionbank/index'
import { Route as NotificationIndexRouteImport } from './routes/notification/index'
import { Route as MentorsIndexRouteImport } from './routes/mentors/index'
import { Route as GradesIndexRouteImport } from './routes/grades/index'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as BoardsIndexRouteImport } from './routes/boards/index'
import { Route as BatchesIndexRouteImport } from './routes/batches/index'
import { Route as TasksIdRouteImport } from './routes/tasks/$id'
import { Route as StudentsIdRouteImport } from './routes/students/$id'
import { Route as MentorsIdRouteImport } from './routes/mentors/$id'
import { Route as GradesIdRouteImport } from './routes/grades/$id'
import { Route as DemoIdRouteImport } from './routes/demo/$id'
import { Route as BoardsIdRouteImport } from './routes/boards/$id'
import { Route as BatchesIdRouteImport } from './routes/batches/$id'
import { Route as DemoAddquestionIndexRouteImport } from './routes/demo/addquestion/index'
import { Route as CoursesTasksIndexRouteImport } from './routes/courses/tasks/index'
import { Route as CoursesQuizesIndexRouteImport } from './routes/courses/quizes/index'
import { Route as CoursesExamsIndexRouteImport } from './routes/courses/exams/index'
import { Route as CoursesIdIndexRouteImport } from './routes/courses/$id/index'
import { Route as TasksSubmissionsSubmissionIdRouteImport } from './routes/tasks/submissions/$submissionId'
import { Route as StudentsEditIdRouteImport } from './routes/students/edit/$id'
import { Route as StudentsStudentIdCourseIdRouteImport } from './routes/students/$studentId/$courseId'
import { Route as QuestionbankQuestionsIdRouteImport } from './routes/questionbank/questions/$id'
import { Route as CoursesExamsIdRouteImport } from './routes/courses/exams/$id'
import { Route as BatchesWhatsappIdRouteImport } from './routes/batches/whatsapp/$id'
import { Route as BatchesViewstudentsBatchIdRouteImport } from './routes/batches/viewstudents/$batchId'
import { Route as BatchesAttendanceBatchIdRouteImport } from './routes/batches/attendance/$batchId'
import { Route as BatchesAddstudentsBatchIdRouteImport } from './routes/batches/addstudents/$batchId'
import { Route as CoursesIdChaptersRouteRouteImport } from './routes/courses/$id/chapters/route'
import { Route as CoursesExamsAddquestionsIndexRouteImport } from './routes/courses/exams/addquestions/index'
import { Route as BatchesAttendanceViewSessionDateRouteImport } from './routes/batches/attendance/$view/$sessionDate'
import { Route as CoursesIdChaptersChapterIdIndexRouteImport } from './routes/courses/$id/chapters/$chapterId/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIndexRoute = QuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionbankIndexRoute = QuestionbankIndexRouteImport.update({
  id: '/questionbank/',
  path: '/questionbank/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationIndexRoute = NotificationIndexRouteImport.update({
  id: '/notification/',
  path: '/notification/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsIndexRoute = MentorsIndexRouteImport.update({
  id: '/mentors/',
  path: '/mentors/',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesIndexRoute = GradesIndexRouteImport.update({
  id: '/grades/',
  path: '/grades/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsIndexRoute = BoardsIndexRouteImport.update({
  id: '/boards/',
  path: '/boards/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesIndexRoute = BatchesIndexRouteImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdRoute = StudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsIdRoute = MentorsIdRouteImport.update({
  id: '/mentors/$id',
  path: '/mentors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesIdRoute = GradesIdRouteImport.update({
  id: '/grades/$id',
  path: '/grades/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIdRoute = DemoIdRouteImport.update({
  id: '/demo/$id',
  path: '/demo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsIdRoute = BoardsIdRouteImport.update({
  id: '/boards/$id',
  path: '/boards/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesIdRoute = BatchesIdRouteImport.update({
  id: '/batches/$id',
  path: '/batches/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAddquestionIndexRoute = DemoAddquestionIndexRouteImport.update({
  id: '/demo/addquestion/',
  path: '/demo/addquestion/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesTasksIndexRoute = CoursesTasksIndexRouteImport.update({
  id: '/courses/tasks/',
  path: '/courses/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesQuizesIndexRoute = CoursesQuizesIndexRouteImport.update({
  id: '/courses/quizes/',
  path: '/courses/quizes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesExamsIndexRoute = CoursesExamsIndexRouteImport.update({
  id: '/courses/exams/',
  path: '/courses/exams/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIdIndexRoute = CoursesIdIndexRouteImport.update({
  id: '/courses/$id/',
  path: '/courses/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksSubmissionsSubmissionIdRoute =
  TasksSubmissionsSubmissionIdRouteImport.update({
    id: '/tasks/submissions/$submissionId',
    path: '/tasks/submissions/$submissionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentsEditIdRoute = StudentsEditIdRouteImport.update({
  id: '/students/edit/$id',
  path: '/students/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdCourseIdRoute =
  StudentsStudentIdCourseIdRouteImport.update({
    id: '/students/$studentId/$courseId',
    path: '/students/$studentId/$courseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const QuestionbankQuestionsIdRoute = QuestionbankQuestionsIdRouteImport.update({
  id: '/questionbank/questions/$id',
  path: '/questionbank/questions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesExamsIdRoute = CoursesExamsIdRouteImport.update({
  id: '/courses/exams/$id',
  path: '/courses/exams/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesWhatsappIdRoute = BatchesWhatsappIdRouteImport.update({
  id: '/batches/whatsapp/$id',
  path: '/batches/whatsapp/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesViewstudentsBatchIdRoute =
  BatchesViewstudentsBatchIdRouteImport.update({
    id: '/batches/viewstudents/$batchId',
    path: '/batches/viewstudents/$batchId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BatchesAttendanceBatchIdRoute =
  BatchesAttendanceBatchIdRouteImport.update({
    id: '/batches/attendance/$batchId',
    path: '/batches/attendance/$batchId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BatchesAddstudentsBatchIdRoute =
  BatchesAddstudentsBatchIdRouteImport.update({
    id: '/batches/addstudents/$batchId',
    path: '/batches/addstudents/$batchId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesIdChaptersRouteRoute = CoursesIdChaptersRouteRouteImport.update({
  id: '/courses/$id/chapters',
  path: '/courses/$id/chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesExamsAddquestionsIndexRoute =
  CoursesExamsAddquestionsIndexRouteImport.update({
    id: '/courses/exams/addquestions/',
    path: '/courses/exams/addquestions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const BatchesAttendanceViewSessionDateRoute =
  BatchesAttendanceViewSessionDateRouteImport.update({
    id: '/batches/attendance/$view/$sessionDate',
    path: '/batches/attendance/$view/$sessionDate',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesIdChaptersChapterIdIndexRoute =
  CoursesIdChaptersChapterIdIndexRouteImport.update({
    id: '/$chapterId/',
    path: '/$chapterId/',
    getParentRoute: () => CoursesIdChaptersRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/batches/$id': typeof BatchesIdRoute
  '/boards/$id': typeof BoardsIdRoute
  '/demo/$id': typeof DemoIdRoute
  '/grades/$id': typeof GradesIdRoute
  '/mentors/$id': typeof MentorsIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/batches/': typeof BatchesIndexRoute
  '/boards/': typeof BoardsIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/grades/': typeof GradesIndexRoute
  '/mentors/': typeof MentorsIndexRoute
  '/notification/': typeof NotificationIndexRoute
  '/questionbank/': typeof QuestionbankIndexRoute
  '/questions/': typeof QuestionsIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/courses/$id/chapters': typeof CoursesIdChaptersRouteRouteWithChildren
  '/batches/addstudents/$batchId': typeof BatchesAddstudentsBatchIdRoute
  '/batches/attendance/$batchId': typeof BatchesAttendanceBatchIdRoute
  '/batches/viewstudents/$batchId': typeof BatchesViewstudentsBatchIdRoute
  '/batches/whatsapp/$id': typeof BatchesWhatsappIdRoute
  '/courses/exams/$id': typeof CoursesExamsIdRoute
  '/questionbank/questions/$id': typeof QuestionbankQuestionsIdRoute
  '/students/$studentId/$courseId': typeof StudentsStudentIdCourseIdRoute
  '/students/edit/$id': typeof StudentsEditIdRoute
  '/tasks/submissions/$submissionId': typeof TasksSubmissionsSubmissionIdRoute
  '/courses/$id/': typeof CoursesIdIndexRoute
  '/courses/exams/': typeof CoursesExamsIndexRoute
  '/courses/quizes/': typeof CoursesQuizesIndexRoute
  '/courses/tasks/': typeof CoursesTasksIndexRoute
  '/demo/addquestion/': typeof DemoAddquestionIndexRoute
  '/batches/attendance/$view/$sessionDate': typeof BatchesAttendanceViewSessionDateRoute
  '/courses/exams/addquestions/': typeof CoursesExamsAddquestionsIndexRoute
  '/courses/$id/chapters/$chapterId/': typeof CoursesIdChaptersChapterIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/batches/$id': typeof BatchesIdRoute
  '/boards/$id': typeof BoardsIdRoute
  '/demo/$id': typeof DemoIdRoute
  '/grades/$id': typeof GradesIdRoute
  '/mentors/$id': typeof MentorsIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/batches': typeof BatchesIndexRoute
  '/boards': typeof BoardsIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/demo': typeof DemoIndexRoute
  '/grades': typeof GradesIndexRoute
  '/mentors': typeof MentorsIndexRoute
  '/notification': typeof NotificationIndexRoute
  '/questionbank': typeof QuestionbankIndexRoute
  '/questions': typeof QuestionsIndexRoute
  '/students': typeof StudentsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/courses/$id/chapters': typeof CoursesIdChaptersRouteRouteWithChildren
  '/batches/addstudents/$batchId': typeof BatchesAddstudentsBatchIdRoute
  '/batches/attendance/$batchId': typeof BatchesAttendanceBatchIdRoute
  '/batches/viewstudents/$batchId': typeof BatchesViewstudentsBatchIdRoute
  '/batches/whatsapp/$id': typeof BatchesWhatsappIdRoute
  '/courses/exams/$id': typeof CoursesExamsIdRoute
  '/questionbank/questions/$id': typeof QuestionbankQuestionsIdRoute
  '/students/$studentId/$courseId': typeof StudentsStudentIdCourseIdRoute
  '/students/edit/$id': typeof StudentsEditIdRoute
  '/tasks/submissions/$submissionId': typeof TasksSubmissionsSubmissionIdRoute
  '/courses/$id': typeof CoursesIdIndexRoute
  '/courses/exams': typeof CoursesExamsIndexRoute
  '/courses/quizes': typeof CoursesQuizesIndexRoute
  '/courses/tasks': typeof CoursesTasksIndexRoute
  '/demo/addquestion': typeof DemoAddquestionIndexRoute
  '/batches/attendance/$view/$sessionDate': typeof BatchesAttendanceViewSessionDateRoute
  '/courses/exams/addquestions': typeof CoursesExamsAddquestionsIndexRoute
  '/courses/$id/chapters/$chapterId': typeof CoursesIdChaptersChapterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/batches/$id': typeof BatchesIdRoute
  '/boards/$id': typeof BoardsIdRoute
  '/demo/$id': typeof DemoIdRoute
  '/grades/$id': typeof GradesIdRoute
  '/mentors/$id': typeof MentorsIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/batches/': typeof BatchesIndexRoute
  '/boards/': typeof BoardsIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/grades/': typeof GradesIndexRoute
  '/mentors/': typeof MentorsIndexRoute
  '/notification/': typeof NotificationIndexRoute
  '/questionbank/': typeof QuestionbankIndexRoute
  '/questions/': typeof QuestionsIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/courses/$id/chapters': typeof CoursesIdChaptersRouteRouteWithChildren
  '/batches/addstudents/$batchId': typeof BatchesAddstudentsBatchIdRoute
  '/batches/attendance/$batchId': typeof BatchesAttendanceBatchIdRoute
  '/batches/viewstudents/$batchId': typeof BatchesViewstudentsBatchIdRoute
  '/batches/whatsapp/$id': typeof BatchesWhatsappIdRoute
  '/courses/exams/$id': typeof CoursesExamsIdRoute
  '/questionbank/questions/$id': typeof QuestionbankQuestionsIdRoute
  '/students/$studentId/$courseId': typeof StudentsStudentIdCourseIdRoute
  '/students/edit/$id': typeof StudentsEditIdRoute
  '/tasks/submissions/$submissionId': typeof TasksSubmissionsSubmissionIdRoute
  '/courses/$id/': typeof CoursesIdIndexRoute
  '/courses/exams/': typeof CoursesExamsIndexRoute
  '/courses/quizes/': typeof CoursesQuizesIndexRoute
  '/courses/tasks/': typeof CoursesTasksIndexRoute
  '/demo/addquestion/': typeof DemoAddquestionIndexRoute
  '/batches/attendance/$view/$sessionDate': typeof BatchesAttendanceViewSessionDateRoute
  '/courses/exams/addquestions/': typeof CoursesExamsAddquestionsIndexRoute
  '/courses/$id/chapters/$chapterId/': typeof CoursesIdChaptersChapterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/batches/$id'
    | '/boards/$id'
    | '/demo/$id'
    | '/grades/$id'
    | '/mentors/$id'
    | '/students/$id'
    | '/tasks/$id'
    | '/batches/'
    | '/boards/'
    | '/courses/'
    | '/demo/'
    | '/grades/'
    | '/mentors/'
    | '/notification/'
    | '/questionbank/'
    | '/questions/'
    | '/students/'
    | '/tasks/'
    | '/courses/$id/chapters'
    | '/batches/addstudents/$batchId'
    | '/batches/attendance/$batchId'
    | '/batches/viewstudents/$batchId'
    | '/batches/whatsapp/$id'
    | '/courses/exams/$id'
    | '/questionbank/questions/$id'
    | '/students/$studentId/$courseId'
    | '/students/edit/$id'
    | '/tasks/submissions/$submissionId'
    | '/courses/$id/'
    | '/courses/exams/'
    | '/courses/quizes/'
    | '/courses/tasks/'
    | '/demo/addquestion/'
    | '/batches/attendance/$view/$sessionDate'
    | '/courses/exams/addquestions/'
    | '/courses/$id/chapters/$chapterId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/batches/$id'
    | '/boards/$id'
    | '/demo/$id'
    | '/grades/$id'
    | '/mentors/$id'
    | '/students/$id'
    | '/tasks/$id'
    | '/batches'
    | '/boards'
    | '/courses'
    | '/demo'
    | '/grades'
    | '/mentors'
    | '/notification'
    | '/questionbank'
    | '/questions'
    | '/students'
    | '/tasks'
    | '/courses/$id/chapters'
    | '/batches/addstudents/$batchId'
    | '/batches/attendance/$batchId'
    | '/batches/viewstudents/$batchId'
    | '/batches/whatsapp/$id'
    | '/courses/exams/$id'
    | '/questionbank/questions/$id'
    | '/students/$studentId/$courseId'
    | '/students/edit/$id'
    | '/tasks/submissions/$submissionId'
    | '/courses/$id'
    | '/courses/exams'
    | '/courses/quizes'
    | '/courses/tasks'
    | '/demo/addquestion'
    | '/batches/attendance/$view/$sessionDate'
    | '/courses/exams/addquestions'
    | '/courses/$id/chapters/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/batches/$id'
    | '/boards/$id'
    | '/demo/$id'
    | '/grades/$id'
    | '/mentors/$id'
    | '/students/$id'
    | '/tasks/$id'
    | '/batches/'
    | '/boards/'
    | '/courses/'
    | '/demo/'
    | '/grades/'
    | '/mentors/'
    | '/notification/'
    | '/questionbank/'
    | '/questions/'
    | '/students/'
    | '/tasks/'
    | '/courses/$id/chapters'
    | '/batches/addstudents/$batchId'
    | '/batches/attendance/$batchId'
    | '/batches/viewstudents/$batchId'
    | '/batches/whatsapp/$id'
    | '/courses/exams/$id'
    | '/questionbank/questions/$id'
    | '/students/$studentId/$courseId'
    | '/students/edit/$id'
    | '/tasks/submissions/$submissionId'
    | '/courses/$id/'
    | '/courses/exams/'
    | '/courses/quizes/'
    | '/courses/tasks/'
    | '/demo/addquestion/'
    | '/batches/attendance/$view/$sessionDate'
    | '/courses/exams/addquestions/'
    | '/courses/$id/chapters/$chapterId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  BatchesIdRoute: typeof BatchesIdRoute
  BoardsIdRoute: typeof BoardsIdRoute
  DemoIdRoute: typeof DemoIdRoute
  GradesIdRoute: typeof GradesIdRoute
  MentorsIdRoute: typeof MentorsIdRoute
  StudentsIdRoute: typeof StudentsIdRoute
  TasksIdRoute: typeof TasksIdRoute
  BatchesIndexRoute: typeof BatchesIndexRoute
  BoardsIndexRoute: typeof BoardsIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  DemoIndexRoute: typeof DemoIndexRoute
  GradesIndexRoute: typeof GradesIndexRoute
  MentorsIndexRoute: typeof MentorsIndexRoute
  NotificationIndexRoute: typeof NotificationIndexRoute
  QuestionbankIndexRoute: typeof QuestionbankIndexRoute
  QuestionsIndexRoute: typeof QuestionsIndexRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  CoursesIdChaptersRouteRoute: typeof CoursesIdChaptersRouteRouteWithChildren
  BatchesAddstudentsBatchIdRoute: typeof BatchesAddstudentsBatchIdRoute
  BatchesAttendanceBatchIdRoute: typeof BatchesAttendanceBatchIdRoute
  BatchesViewstudentsBatchIdRoute: typeof BatchesViewstudentsBatchIdRoute
  BatchesWhatsappIdRoute: typeof BatchesWhatsappIdRoute
  CoursesExamsIdRoute: typeof CoursesExamsIdRoute
  QuestionbankQuestionsIdRoute: typeof QuestionbankQuestionsIdRoute
  StudentsStudentIdCourseIdRoute: typeof StudentsStudentIdCourseIdRoute
  StudentsEditIdRoute: typeof StudentsEditIdRoute
  TasksSubmissionsSubmissionIdRoute: typeof TasksSubmissionsSubmissionIdRoute
  CoursesIdIndexRoute: typeof CoursesIdIndexRoute
  CoursesExamsIndexRoute: typeof CoursesExamsIndexRoute
  CoursesQuizesIndexRoute: typeof CoursesQuizesIndexRoute
  CoursesTasksIndexRoute: typeof CoursesTasksIndexRoute
  DemoAddquestionIndexRoute: typeof DemoAddquestionIndexRoute
  BatchesAttendanceViewSessionDateRoute: typeof BatchesAttendanceViewSessionDateRoute
  CoursesExamsAddquestionsIndexRoute: typeof CoursesExamsAddquestionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/': {
      id: '/questions/'
      path: '/questions'
      fullPath: '/questions/'
      preLoaderRoute: typeof QuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionbank/': {
      id: '/questionbank/'
      path: '/questionbank'
      fullPath: '/questionbank/'
      preLoaderRoute: typeof QuestionbankIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification/': {
      id: '/notification/'
      path: '/notification'
      fullPath: '/notification/'
      preLoaderRoute: typeof NotificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors/': {
      id: '/mentors/'
      path: '/mentors'
      fullPath: '/mentors/'
      preLoaderRoute: typeof MentorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades/': {
      id: '/grades/'
      path: '/grades'
      fullPath: '/grades/'
      preLoaderRoute: typeof GradesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/': {
      id: '/boards/'
      path: '/boards'
      fullPath: '/boards/'
      preLoaderRoute: typeof BoardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/': {
      id: '/batches/'
      path: '/batches'
      fullPath: '/batches/'
      preLoaderRoute: typeof BatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id': {
      id: '/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof StudentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors/$id': {
      id: '/mentors/$id'
      path: '/mentors/$id'
      fullPath: '/mentors/$id'
      preLoaderRoute: typeof MentorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades/$id': {
      id: '/grades/$id'
      path: '/grades/$id'
      fullPath: '/grades/$id'
      preLoaderRoute: typeof GradesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/$id': {
      id: '/demo/$id'
      path: '/demo/$id'
      fullPath: '/demo/$id'
      preLoaderRoute: typeof DemoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$id': {
      id: '/boards/$id'
      path: '/boards/$id'
      fullPath: '/boards/$id'
      preLoaderRoute: typeof BoardsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/$id': {
      id: '/batches/$id'
      path: '/batches/$id'
      fullPath: '/batches/$id'
      preLoaderRoute: typeof BatchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/addquestion/': {
      id: '/demo/addquestion/'
      path: '/demo/addquestion'
      fullPath: '/demo/addquestion/'
      preLoaderRoute: typeof DemoAddquestionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/tasks/': {
      id: '/courses/tasks/'
      path: '/courses/tasks'
      fullPath: '/courses/tasks/'
      preLoaderRoute: typeof CoursesTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/quizes/': {
      id: '/courses/quizes/'
      path: '/courses/quizes'
      fullPath: '/courses/quizes/'
      preLoaderRoute: typeof CoursesQuizesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/exams/': {
      id: '/courses/exams/'
      path: '/courses/exams'
      fullPath: '/courses/exams/'
      preLoaderRoute: typeof CoursesExamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$id/': {
      id: '/courses/$id/'
      path: '/courses/$id'
      fullPath: '/courses/$id/'
      preLoaderRoute: typeof CoursesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/submissions/$submissionId': {
      id: '/tasks/submissions/$submissionId'
      path: '/tasks/submissions/$submissionId'
      fullPath: '/tasks/submissions/$submissionId'
      preLoaderRoute: typeof TasksSubmissionsSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/edit/$id': {
      id: '/students/edit/$id'
      path: '/students/edit/$id'
      fullPath: '/students/edit/$id'
      preLoaderRoute: typeof StudentsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId/$courseId': {
      id: '/students/$studentId/$courseId'
      path: '/students/$studentId/$courseId'
      fullPath: '/students/$studentId/$courseId'
      preLoaderRoute: typeof StudentsStudentIdCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionbank/questions/$id': {
      id: '/questionbank/questions/$id'
      path: '/questionbank/questions/$id'
      fullPath: '/questionbank/questions/$id'
      preLoaderRoute: typeof QuestionbankQuestionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/exams/$id': {
      id: '/courses/exams/$id'
      path: '/courses/exams/$id'
      fullPath: '/courses/exams/$id'
      preLoaderRoute: typeof CoursesExamsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/whatsapp/$id': {
      id: '/batches/whatsapp/$id'
      path: '/batches/whatsapp/$id'
      fullPath: '/batches/whatsapp/$id'
      preLoaderRoute: typeof BatchesWhatsappIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/viewstudents/$batchId': {
      id: '/batches/viewstudents/$batchId'
      path: '/batches/viewstudents/$batchId'
      fullPath: '/batches/viewstudents/$batchId'
      preLoaderRoute: typeof BatchesViewstudentsBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/attendance/$batchId': {
      id: '/batches/attendance/$batchId'
      path: '/batches/attendance/$batchId'
      fullPath: '/batches/attendance/$batchId'
      preLoaderRoute: typeof BatchesAttendanceBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/addstudents/$batchId': {
      id: '/batches/addstudents/$batchId'
      path: '/batches/addstudents/$batchId'
      fullPath: '/batches/addstudents/$batchId'
      preLoaderRoute: typeof BatchesAddstudentsBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$id/chapters': {
      id: '/courses/$id/chapters'
      path: '/courses/$id/chapters'
      fullPath: '/courses/$id/chapters'
      preLoaderRoute: typeof CoursesIdChaptersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/exams/addquestions/': {
      id: '/courses/exams/addquestions/'
      path: '/courses/exams/addquestions'
      fullPath: '/courses/exams/addquestions/'
      preLoaderRoute: typeof CoursesExamsAddquestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/attendance/$view/$sessionDate': {
      id: '/batches/attendance/$view/$sessionDate'
      path: '/batches/attendance/$view/$sessionDate'
      fullPath: '/batches/attendance/$view/$sessionDate'
      preLoaderRoute: typeof BatchesAttendanceViewSessionDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$id/chapters/$chapterId/': {
      id: '/courses/$id/chapters/$chapterId/'
      path: '/$chapterId'
      fullPath: '/courses/$id/chapters/$chapterId/'
      preLoaderRoute: typeof CoursesIdChaptersChapterIdIndexRouteImport
      parentRoute: typeof CoursesIdChaptersRouteRoute
    }
  }
}

interface CoursesIdChaptersRouteRouteChildren {
  CoursesIdChaptersChapterIdIndexRoute: typeof CoursesIdChaptersChapterIdIndexRoute
}

const CoursesIdChaptersRouteRouteChildren: CoursesIdChaptersRouteRouteChildren =
  {
    CoursesIdChaptersChapterIdIndexRoute: CoursesIdChaptersChapterIdIndexRoute,
  }

const CoursesIdChaptersRouteRouteWithChildren =
  CoursesIdChaptersRouteRoute._addFileChildren(
    CoursesIdChaptersRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  BatchesIdRoute: BatchesIdRoute,
  BoardsIdRoute: BoardsIdRoute,
  DemoIdRoute: DemoIdRoute,
  GradesIdRoute: GradesIdRoute,
  MentorsIdRoute: MentorsIdRoute,
  StudentsIdRoute: StudentsIdRoute,
  TasksIdRoute: TasksIdRoute,
  BatchesIndexRoute: BatchesIndexRoute,
  BoardsIndexRoute: BoardsIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  DemoIndexRoute: DemoIndexRoute,
  GradesIndexRoute: GradesIndexRoute,
  MentorsIndexRoute: MentorsIndexRoute,
  NotificationIndexRoute: NotificationIndexRoute,
  QuestionbankIndexRoute: QuestionbankIndexRoute,
  QuestionsIndexRoute: QuestionsIndexRoute,
  StudentsIndexRoute: StudentsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  CoursesIdChaptersRouteRoute: CoursesIdChaptersRouteRouteWithChildren,
  BatchesAddstudentsBatchIdRoute: BatchesAddstudentsBatchIdRoute,
  BatchesAttendanceBatchIdRoute: BatchesAttendanceBatchIdRoute,
  BatchesViewstudentsBatchIdRoute: BatchesViewstudentsBatchIdRoute,
  BatchesWhatsappIdRoute: BatchesWhatsappIdRoute,
  CoursesExamsIdRoute: CoursesExamsIdRoute,
  QuestionbankQuestionsIdRoute: QuestionbankQuestionsIdRoute,
  StudentsStudentIdCourseIdRoute: StudentsStudentIdCourseIdRoute,
  StudentsEditIdRoute: StudentsEditIdRoute,
  TasksSubmissionsSubmissionIdRoute: TasksSubmissionsSubmissionIdRoute,
  CoursesIdIndexRoute: CoursesIdIndexRoute,
  CoursesExamsIndexRoute: CoursesExamsIndexRoute,
  CoursesQuizesIndexRoute: CoursesQuizesIndexRoute,
  CoursesTasksIndexRoute: CoursesTasksIndexRoute,
  DemoAddquestionIndexRoute: DemoAddquestionIndexRoute,
  BatchesAttendanceViewSessionDateRoute: BatchesAttendanceViewSessionDateRoute,
  CoursesExamsAddquestionsIndexRoute: CoursesExamsAddquestionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
